name: Node.js CI/CD

on:
  push:
    branches: [main] # only run on main branch
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.7.0"

      - name: Install dependencies
        run: npm install

      # placeholder for env vars

      - name: Build Docker image
        run: docker build -t registry.digitalocean.com/streamtogether-backend/streamtogether:latest .

      - name: Login to DigitalOcean Container Registry
        run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push registry.digitalocean.com/streamtogether-backend/streamtogether:latest

      - name: Setup SSH Key and Deploy to Droplet
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "\
          docker stop streamtogether-backend && \
          docker rm streamtogether-backend && \
          docker pull registry.digitalocean.com/streamtogether-backend/streamtogether:latest && \
          docker run -d -p 2000:2000 --name streamtogether-backend registry.digitalocean.com/streamtogether-backend/streamtogether:latest"
